blueprint:
  name: Toogle Light Wall Switch
  description: 'Turn on/off a light/switch when a switch is toogled'
  domain: automation
  source_url: https://github.com/AlexandrePautet/ha-blueprints/blob/main/toogle_light_wall_switch.yaml
  author: Alexandre Pautet
  input:
    switch_entity:
      name: Switch device
      description: The switch you toogle
      selector:
        entity:
          filter:
            domain: binary_sensor
    light_target_entity:
      name: Light
      description: The light whose brightness will be changed
      selector:
        entity:
          domain:
          - light
          - switch
          multiple: false
          reorder: false
    circadien_entity:
      name: Input Circadien
      description: Circadien entity
      selector:
        text:
          multiline: false
          multiple: false
    dayornight_value:
      name: Day night string
      description: Day or night string
      selector:
        text:
          multiline: false
          multiple: false
    brightness_day_value:
      name: Brightness Day value
      description: Brightness day value
      selector:
        text:
          multiline: false
          multiple: false
    brightness_night_value:
      name: Brightness Night value
      description: Brightness Night value
      selector:
        text:
          multiline: false
          multiple: false

trigger_variables:
  circadien_entity: !input circadien_entity
  dayornight_value: !input dayornight_value
  brightness_day_value: !input brightness_day_value
  brightness_night_value: !input brightness_night_value

triggers:
  - trigger: state
    entity_id: !input switch_entity
    from: 'off'
    to: 'on'
  - trigger: state
    entity_id: !input switch_entity
    from: 'on'
    to: 'off'

actions:
  - alias: Toogle the light
    action: light.toggle
    target:
      entity_id: !input light_target_entity
    data:
      brightness: >
        {% if is_state(circadien_entity, dayornight_value) %}
        {{ states(brightness_day_value)|int }}
        {% else %}
        {{ states(brightness_night_value)|int }}
        {% endif %}
  - alias: Toogle the switch
    action: switch.toggle
    target:
      entity_id: !input light_target_entity
