blueprint:
  name: Toogle Light Wall Switch
  description: Toogle a light when a switch is toogled
  domain: automation
  source_url: https://github.com/AlexandrePautet/ha-blueprints/blob/main/toogle_light_wall_switch.yaml
  author: Alexandre Pautet
  input:
    switch_entity:
      name: Switch device
      description: The switch you toogle
      selector:
        target:
          entity:
            domain: switch
    light_target_entity:
      name: Light
      description: The light to be toggled
      selector:
        target:
          entity:
          - domain: light

triggers:
  - trigger: state
    entity_id: !input topic_action_entity
    from: "off"
    to: "on"
  - trigger: state
    entity_id: !input topic_action_entity
    from: "on"
    to: "off"

actions:
  - alias: Toogle the light
    action: light.toggle
    target: !input light_target_entity
