blueprint:
  name: Update Light Brightness
  description: 'Change light brightness with the value of an input-numeric'
  domain: automation
  source_url: https://github.com/AlexandrePautet/ha-blueprints/blob/main/update_light_brightness.yaml
  author: Alexandre Pautet
  input:
    input_number_entity:
      name: Input Number Entity
      description: The input-number with the brightness value
      selector:
        entity:
          filter:
            domain: input_number
    light_target_entity:
      name: Light
      description: The light whose brightness will be modified
      selector:
        entity:
          domain: light

trigger_variables:
  input_number_entity: !input input_number_entity
  light_target_entity: !input light_target_entity
  
triggers:
  - trigger: state
    entity_id: !input input_number_entity

conditions:
  - condition: state
    entity_id: !input light_target_entity
    state: "on"

actions:
  - alias: Change brightness
    action: light.turn_on
    target:
      entity_id: !input light_target_entity
    data:
      brightness: "{{ states(input_number_entity)|int }}"
